language: python
python:
  - "3.6"

install:
  - pip3 install -r requirements.txt

before_script:
  - sudo apt-get install graphviz
  - sudo apt-get install antlr4

script:
  - cd src/antlr_parser
  - antlr4 -Dlanguage=Python3 Gram.g4
  - cd ../antlr_regex
  - antlr4 -Dlanguage=Python3 Rule.g4
  - cd ..
  - python3 -m pytest ../test -v