language: python
python:
  - "3.6"

install:
  - pip3 install rdflib
  - pip3 install pyformlang
  - pip3 install pygraphviz
  - pip3 install grammpy

before_script:
  - sudo apt-get install graphviz
  - cd src

script:
  - python3 -m pytest ../test -v